#include: package:lints/recommended.yaml
#include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - packages
  enable-experiment:
    - non-nullable
  plugins:
    - dart_code_metrics

linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - curly_braces_in_flow_control_structures

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cycloramic-complexity: 5
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 250
  metrics-exclude:
    - test/**
  rules:
    - avoid-global-state
    - avoid-ignoring-return-values:
      exclude:
        - test/**
    - avoid-missing-enum-constant-in-map
    #    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-non-null-assertion
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering-extended:
        exclude:
          - test/**
    - member-ordering:
        exclude:
          - test/**
    - newline-before-return:
        exclude:
          - test/**
    - no-boolean-literal-compare
    - no-empty-block
    #    - no-equal-arguments:
    #        ignored-parameters:
    #          - height
    #          - width
    - no-equal-then-else
    - no-magic-number:
        exclude:
          - test/**
          - lib/ui/**
          - lib/theme/**
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        exceptions: [ 'z', ]
        max-identifier-length: 45
        min-identifier-length: 3
    - prefer-correct-type-name:
        #        excluded: [ '' ]
        min-length: 3
        max-length: 40
    - prefer-first:
        exclude:
          - test/**
    - prefer-last:
        exclude:
          - test/**
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-trailing-comma:
        exclude:
          - test/**

    # Flutter specific
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-intl-name
    - provide-correct-intl-args
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-const-border-radius
